export const USER_STATE_CHANGE = "USER_STATE_CHANGE";
export const ORG_LIST_LOAD = "ORG_LIST_LOAD";
export const CURRENT_USER_GET_ANNOUNCEMENTS = "CURRENT_USER_GET_ANNOUNCEMENTS";
export const CHAPTER_LIST_LOAD = "CHAPTER_LIST_LOAD";
export const USER_GET_PROFILE_IMAGE = "USER_GET_PROFILE_IMAGE";