// ADMIN
export const UNVERIFIED_LIST_LOAD = "UNVERIFIED_LIST_LOAD";
export const VERIFY = "VERIFY";
export const DENY = "DENY";

// ANNOUNCEMENT
export const CURRENT_USER_GET_ANNOUNCEMENTS = "CURRENT_USER_GET_ANNOUNCEMENTS";
export const CREATE_ANNOUNCEMENT = "CREATE_ANNOUNCEMENT";
export const DELETE_ANNOUNCEMENT = "DELETE_ANNOUNCEMENT";

// AUTH
export const USER_STATE_CHANGE = "USER_STATE_CHANGE";
export const UPDATE_PROFILE_IMAGE = "UPDATE_PROFILE_IMAGE";

// ORGS
export const ORG_LIST_LOAD = "ORG_LIST_LOAD";
export const CHAPTER_LIST_LOAD = "CHAPTER_LIST_LOAD";
export const UPDATE_SELECTED_ORG = "UPDATE_SELECTED_ORG";
export const UPDATE_SELECTED_CHAPTER = "UPDATE_SELECTED_CHAPTER";