// ADMIN
export const UNVERIFIED_LIST_LOAD = "UNVERIFIED_LIST_LOAD";
export const VERIFY = "VERIFY";
export const DENY = "DENY";

// ANNOUNCEMENT
export const CURRENT_USER_GET_ANNOUNCEMENTS = "CURRENT_USER_GET_ANNOUNCEMENTS";
export const CREATE_ANNOUNCEMENT = "CREATE_ANNOUNCEMENT";
export const DELETE_ANNOUNCEMENT = "DELETE_ANNOUNCEMENT";
export const LIKE_ANNOUNCEMENT = "LIKE_ANNOUNCEMENT";
export const UNLIKE_ANNOUNCEMENT = "UNLIKE_ANNOUNCEMENT";

// AUTH
export const USER_STATE_CHANGE = "USER_STATE_CHANGE";
export const UPDATE_PROFILE_IMAGE = "UPDATE_PROFILE_IMAGE";

// CHAT
export const CREATE_MESSAGE = "CREATE_MESSAGE";
export const GET_USER_MESSAGES = "GET_USER_MESSAGES";
export const GET_MESSAGE_PREVIEWS = "GET_MESSAGE_PREVIEWS"

// ORGS
export const ORG_LIST_LOAD = "ORG_LIST_LOAD";
export const CHAPTER_LIST_LOAD = "CHAPTER_LIST_LOAD";
export const UPDATE_SELECTED_ORG = "UPDATE_SELECTED_ORG";
export const UPDATE_SELECTED_CHAPTER = "UPDATE_SELECTED_CHAPTER";

// USERS
export const GET_USERS_BY_CHAPTER = "GET_USERS_BY_CHAPTER";